version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx-conf:/etc/nginx/conf.d
            - .:/symfony
    fpm:
        build: docker/fpm
        volumes:
            - .:/symfony
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_RANDOM_ROOT_PASSWORD
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "81:80"
        environment:
            PMA_HOST: mysql
